name: Standard

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Standard
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - # https://github.com/actions/checkout
        name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - # https://github.com/extractions/setup-just
        name: Install just
        uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b # v3.1.0

      - # https://github.com/pnpm/action-setup
        name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          run_install: false

      - # https://github.com/actions/setup-node
        name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Biome
        run: just lint

      - name: TypeScript
        run: just check

      - name: Knip
        run: just knip

      - name: Vitest
        run: just test
